version: '3'

services:
  nodejsapp:
    build: ./nodejsapp
    ports:
      - 8085:8085
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    ports:
      - 9000:9000
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
