variables:
  CONTAINER_IMAGE: anaselhajjaji/nodejsapp
  DOCKER_HOST: tcp://192.168.0.23:2375
  SONAR_HOST: http://192.168.0.23:8091
stages:
  - analysis
  - test
  - build
  - deploy
analysis:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: $SONAR_HOST
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner -Dsonar.login=$SONAR_TOKEN
test:
  stage: test
  image: node:8.12.0-alpine
  script:
    - npm i
    - npm install -g mocha
    - npm test
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker image build -t $CONTAINER_IMAGE:$CI_BUILD_REF -t $CONTAINER_IMAGE:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker image push $CONTAINER_IMAGE:latest
    - docker image push $CONTAINER_IMAGE:$CI_BUILD_REF
  only:
    - master
deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --update curl
    - curl -XPOST $WWW_WEBHOOK
  only:
    - master
